version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: nq-capital-postgres
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    mem_limit: 512m
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    container_name: nq-capital-redis
    restart: no
    ports:
      - '6379:6379'
    command: redis-server --save '' --appendonly no --loglevel warning --protected-mode no
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local
  cache:
    driver: local
