projects:
  investors-portal-web:
    schema: "./schema.gql"
    documents: "apps/investors-portal-web/**/*.gql"
    exclude: "apps/investors-portal-web/.next/**/*"
  backoffice-web:
    schema: "./schema.gql"
    documents:
      - "apps/backoffice-web/**/*.gql"
      - "apps/backoffice-web/**/*.tsx"
    exclude: "apps/backoffice-web/.next/**/*"
